"""Versao final com biblioteca de exercicios por usuario

Revision ID: ee57171771ae
Revises: 
Create Date: 2025-10-24 15:00:33.409793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee57171771ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('exercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('grupo_muscular', sa.String(length=50), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_medicao', sa.DateTime(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('circunferencia_braco_cm', sa.Float(), nullable=True),
    sa.Column('circunferencia_cintura_cm', sa.Float(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_treino', sa.DateTime(), nullable=False),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('hora_fim', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treino_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercicio_registrado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_treino', sa.Integer(), nullable=False),
    sa.Column('id_exercicio', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_exercicio'], ['exercicio.id'], ),
    sa.ForeignKeyConstraint(['id_treino'], ['treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_exercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('id_template', sa.Integer(), nullable=False),
    sa.Column('id_exercicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_exercicio'], ['exercicio.id'], ),
    sa.ForeignKeyConstraint(['id_template'], ['treino_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.Integer(), nullable=False),
    sa.Column('repeticoes', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('id_exercicio_registrado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_exercicio_registrado'], ['exercicio_registrado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serie')
    op.drop_table('template_exercicio')
    op.drop_table('exercicio_registrado')
    op.drop_table('treino_template')
    op.drop_table('treino')
    op.drop_table('medicao')
    op.drop_table('exercicio')
    op.drop_table('usuario')
    # ### end Alembic commands ###
